import { Airport } from "@/types/flight";

export const AIRPORTS: Airport[] = [
  { code: "DEL", city: "New Delhi", name: "Indira Gandhi International", aliases: ["delhi"] },
  { code: "BOM", city: "Mumbai", name: "Chhatrapati Shivaji Maharaj International", aliases: ["bombay"] },
  { code: "BLR", city: "Bengaluru", name: "Kempegowda International", aliases: ["bangalore"] },
  { code: "HYD", city: "Hyderabad", name: "Rajiv Gandhi International" },
  { code: "MAA", city: "Chennai", name: "Chennai International", aliases: ["madras"] },
  { code: "CCU", city: "Kolkata", name: "Netaji Subhas Chandra Bose International", aliases: ["calcutta"] },
  { code: "PNQ", city: "Pune", name: "Pune Airport" },
  { code: "AMD", city: "Ahmedabad", name: "Sardar Vallabhbhai Patel International" },
  { code: "GOI", city: "Goa (Dabolim)", name: "Manohar International", aliases: ["goa"] },
  { code: "GOX", city: "Goa (Mopa)", name: "Manohar International Airport, Mopa", aliases: ["goa"] },
  { code: "COK", city: "Kochi", name: "Cochin International", aliases: ["cochin"] },
  { code: "JAI", city: "Jaipur", name: "Jaipur International" },
  { code: "LKO", city: "Lucknow", name: "Chaudhary Charan Singh International" },
  { code: "IXC", city: "Chandigarh", name: "Chandigarh International" },
  { code: "GAU", city: "Guwahati", name: "Lokpriya Gopinath Bordoloi International" },
  { code: "PAT", city: "Patna", name: "Jay Prakash Narayan International" },
  { code: "IXB", city: "Bagdogra", name: "Bagdogra Airport", aliases: ["siliguri", "darjeeling"] },
  { code: "ATQ", city: "Amritsar", name: "Sri Guru Ram Dass Jee International" },
  { code: "IXR", city: "Ranchi", name: "Birsa Munda Airport" },
  { code: "BBI", city: "Bhubaneswar", name: "Biju Patnaik International" },
  { code: "IXZ", city: "Port Blair", name: "Veer Savarkar International", aliases: ["andaman"] },
  { code: "NAG", city: "Nagpur", name: "Dr. Babasaheb Ambedkar International" },
  { code: "IDR", city: "Indore", name: "Devi Ahilya Bai Holkar Airport" },
  { code: "VNS", city: "Varanasi", name: "Lal Bahadur Shastri International", aliases: ["banaras", "kashi"] },
  { code: "SXR", city: "Srinagar", name: "Sheikh ul-Alam International" },
  { code: "IXJ", city: "Jammu", name: "Jammu Airport" },
  { code: "RPR", city: "Raipur", name: "Swami Vivekananda Airport" },
  { code: "IXA", city: "Agartala", name: "Maharaja Bir Bikram Airport" },
  { code: "IMF", city: "Imphal", name: "Bir Tikendrajit International" },
  { code: "AJL", city: "Aizawl", name: "Lengpui Airport" },
  { code: "IXS", city: "Silchar", name: "Silchar Airport" },
  { code: "DIB", city: "Dibrugarh", name: "Dibrugarh Airport" },
  { code: "IXD", city: "Allahabad (Prayagraj)", name: "Prayagraj Airport", aliases: ["allahabad", "prayagraj"] },
  { code: "GWL", city: "Gwalior", name: "Rajmata Vijaya Raje Scindia Airport" },
  { code: "IXU", city: "Aurangabad", name: "Chhatrapati Sambhajinagar Airport" },
  { code: "STV", city: "Surat", name: "Surat Airport" },
  { code: "BDQ", city: "Vadodara", name: "Vadodara Airport", aliases: ["baroda"] },
  { code: "RAJ", city: "Rajkot", name: "Rajkot International" },
  { code: "BHJ", city: "Bhuj", name: "Bhuj Airport" },
  { code: "UDR", city: "Udaipur", name: "Maharana Pratap Airport" },
  { code: "JDH", city: "Jodhpur", name: "Jodhpur Airport" },
  { code: "BKB", city: "Bikaner", name: "Nal Airport" },
  { code: "KTU", city: "Kota", name: "Kota Airport" },
  { code: "IXE", city: "Mangaluru", name: "Mangaluru International", aliases: ["mangalore"] },
  { code: "HBX", city: "Hubballi", name: "Hubballi Airport", aliases: ["hubli"] },
  { code: "IXG", city: "Belagavi", name: "Belagavi Airport", aliases: ["belgaum"] },
  { code: "VGA", city: "Vijayawada", name: "Vijayawada International" },
  { code: "VTZ", city: "Visakhapatnam", name: "Visakhapatnam International", aliases: ["vizag"] },
  { code: "TIR", city: "Tirupati", name: "Tirupati Airport" },
  { code: "RJA", city: "Rajahmundry", name: "Rajahmundry Airport" },
  { code: "CJB", city: "Coimbatore", name: "Coimbatore International" },
  { code: "MDU", city: "Madurai", name: "Madurai International" },
  { code: "TRZ", city: "Tiruchirappalli", name: "Tiruchirappalli International", aliases: ["trichy"] },
  { code: "TRV", city: "Thiruvananthapuram", name: "Trivandrum International", aliases: ["trivandrum"] },
  { code: "CCJ", city: "Kozhikode", name: "Calicut International", aliases: ["calicut"] },
  { code: "PNY", city: "Puducherry", name: "Puducherry Airport", aliases: ["pondicherry"] },
  { code: "IXL", city: "Leh", name: "Kushok Bakula Rimpochee Airport" },
  { code: "DED", city: "Dehradun", name: "Jolly Grant Airport" },
  { code: "PGH", city: "Pantnagar", name: "Pantnagar Airport" },
  { code: "SLV", city: "Shimla", name: "Shimla Airport" },
  { code: "KUU", city: "Kullu Manali", name: "Bhuntar Airport", aliases: ["manali", "kullu"] },
  { code: "DHM", city: "Dharamshala", name: "Kangra Airport" },
  { code: "IXW", city: "Jamshedpur", name: "Sonari Airport" },
  { code: "PYB", city: "Jeypore", name: "Jeypore Airport" },
];

export function findAirport(code: string): Airport | undefined {
  return AIRPORTS.find((a) => a.code === code);
}

export function formatAirport(a: Airport): string {
  return `${a.city} (${a.code})`;
}
